### ISSUE TITLE
Error: argument `$color` of `darken($color, $amount)` must be a color

### ISSUE THREAD

**Issue by weilianglei123** [NativeScript/nativescript-marketplace-demo#283] opened 2017-11-26 15:47 UTC
when i run 'tns run ios ' have issue.

Found peer node-sass
Error: argument `$color` of `darken($color, $amount)` must be a color

       Backtrace:
        node_modules/bootstrap/scss/_variables.scss:142, in function `darken`
        node_modules/bootstrap/scss/_variables.scss:142
        on line 142 of node_modules/bootstrap/scss/_variables.scss
>> $link-hover-color:          darken($link-color, 15%) !default;
   ----------------------------^

**Comment by vchimev** [comment] 2017-11-29 12:58
https://github.com/NativeScript/theme/issues/139

**Comment by NickIliev** [comment] 2018-05-30 12:50
Closing as the issue is no longer reproducible in this application (SASS removed in favour of CSS)

**Closed by NickIliev** 2018-05-30 12:50 UTC
