### ISSUE TITLE
Marketplace item list is disappearing

### ISSUE THREAD

**Issue by PawelOwczarekFalcon** [NativeScript/nativescript-marketplace-demo#278] opened 2017-10-03 10:28 UTC
I do not know how to describe this issue. Just look video https://youtu.be/yT-olB32LOg

I tested this demo app on android (galaxy alpha - android v.5.0.1), the same issue is in android emulator. After that I downloaded app from google play and it works fine.

**Comment by NickIliev** [comment] 2018-05-30 12:51
Closing as the issue is not reproducible with the latest update

**Closed by NickIliev** 2018-05-30 12:51 UTC
Labels: os: android
